# Generated by Django 4.2.3 on 2023-07-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtrans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
